-- Separate live streams from regular videos in daily picks.
-- Adds video_type column, widens rank to 1-10, adds is_live_stream to candidates,
-- and creates page_events table for anonymous click analytics.

-- 1. Add video_type to youtube_daily_picks
ALTER TABLE youtube_daily_picks
  ADD COLUMN IF NOT EXISTS video_type TEXT NOT NULL DEFAULT 'video'
    CHECK (video_type IN ('video', 'live'));

-- 2. Drop old unique constraint (name generated by Postgres from original CREATE TABLE)
ALTER TABLE youtube_daily_picks
  DROP CONSTRAINT IF EXISTS youtube_daily_picks_pick_date_rank_key;

-- 3. Drop old rank check (1-3) and replace with 1-10
ALTER TABLE youtube_daily_picks
  DROP CONSTRAINT IF EXISTS youtube_daily_picks_rank_check;

ALTER TABLE youtube_daily_picks
  ADD CONSTRAINT youtube_daily_picks_rank_check
    CHECK (rank BETWEEN 1 AND 10);

-- 4. New unique constraint includes video_type
ALTER TABLE youtube_daily_picks
  ADD CONSTRAINT youtube_daily_picks_pick_date_rank_video_type_key
    UNIQUE (pick_date, rank, video_type);

-- 5. Add is_live_stream to candidates debug table
ALTER TABLE youtube_daily_candidates
  ADD COLUMN IF NOT EXISTS is_live_stream BOOLEAN NOT NULL DEFAULT false;

-- 6. Page events table for anonymous UI analytics (expand-button clicks, etc.)
CREATE TABLE IF NOT EXISTS page_events (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type  TEXT        NOT NULL,
  metadata    JSONB,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_page_events_type     ON page_events(event_type);
CREATE INDEX IF NOT EXISTS idx_page_events_occurred ON page_events(occurred_at DESC);
