/**
 * Tweet draft generator for daily YouTube picks.
 *
 * Generates one tweet per day using the rank-1 YouTube pick.
 * Template A: has creator Twitter handle → includes @mention
 * Template B: no handle available → stronger hook, no ping
 *
 * The hook sentence is generated by GPT-4o-mini (temperature 0.7) to ensure
 * daily variation so consecutive tweets don't look identical to spam filters.
 */

import { getOpenAIClient } from "@/lib/ai/openai-client";

function getNewsBaseUrl(): string {
  return process.env.NEXT_PUBLIC_APP_URL ?? "https://propfirmhub.com";
}
const UTM_PARAMS = "utm_source=twitter&utm_medium=bot&utm_campaign=daily-picks";
// Each URL counts as ~23 chars in Twitter's character counter regardless of actual length.
const TWITTER_URL_CHAR_COUNT = 23;
const TWEET_MAX_CHARS = 280;

export interface YouTubePickInput {
  videoId: string;
  title: string;
  channelName: string;
  channelId: string;
  videoUrl: string;
  aiSummary: string | null;
  twitterHandle: string | null; // from youtube_channels.twitter_handle
}

export interface TweetDraft {
  tweetText: string;
  template: "A" | "B";
  creatorHandle: string | null;
  videoTitle: string;
  videoUrl: string;
  newsUrl: string;
  charCount: number;
}

/**
 * Generate a hook sentence for a video using GPT-4o-mini.
 * Returns a fallback hook on failure so the draft pipeline never dies.
 */
async function generateHook(
  title: string,
  channelName: string,
  summary: string | null
): Promise<string> {
  const openai = getOpenAIClient();
  const summaryLine = summary ? `\nAI summary: "${summary}"` : "";

  const prompt = `You write punchy, engaging one-sentence hooks for tweets about prop trading YouTube videos.

Video title: "${title}"
Channel: ${channelName}${summaryLine}

Write a single hook sentence (<80 characters) that makes a prop trader want to watch this video.
Rules:
- Do NOT start with "I", "We", "Check out", or "Watch"
- Focus on the insight or value the video delivers
- No hashtags, no emojis, no quotes
- Output ONLY the hook sentence, nothing else`;

  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.7,
      max_tokens: 40,
    });
    const hook = completion.choices[0]?.message?.content?.trim();
    if (hook && hook.length > 0 && hook.length <= 120) return hook;
    return buildFallbackHook(title);
  } catch {
    return buildFallbackHook(title);
  }
}

function buildFallbackHook(title: string): string {
  // Trim title to fit as a fallback hook
  const trimmed = title.length > 75 ? title.slice(0, 72) + "…" : title;
  return trimmed;
}

/**
 * Assemble the full tweet text from parts, ensuring it fits within 280 chars.
 * Twitter counts each URL as 23 chars regardless of actual length.
 */
function assembleTweet(
  hook: string,
  summary: string | null,
  videoUrl: string,
  newsUrl: string,
  creatorHandle: string | null
): string {
  const summaryLine = summary
    ? summary.length > 100
      ? summary.slice(0, 97) + "…"
      : summary
    : null;

  const viaLine = creatorHandle ? `Via @${creatorHandle} 📺 ${videoUrl}` : `📺 ${videoUrl}`;
  const ctaLine = `More: ${newsUrl}`;

  // Build candidate with real URLs for length calculation.
  // Replace each URL with a 23-char placeholder to mirror Twitter's counter.
  function twitterLength(text: string): number {
    // Count how many URLs are in the text (rough: count http occurrences)
    const urlMatches = text.match(/https?:\/\/\S+/g) ?? [];
    let len = text.length;
    for (const url of urlMatches) {
      len = len - url.length + TWITTER_URL_CHAR_COUNT;
    }
    return len;
  }

  const parts = [hook];
  if (summaryLine) parts.push(summaryLine);
  parts.push(viaLine);
  parts.push(ctaLine);
  parts.push("#PropTrading");

  let text = parts.join("\n\n");

  // If over limit, drop summary first, then truncate hook
  if (twitterLength(text) > TWEET_MAX_CHARS && summaryLine) {
    const partsNoSummary = [hook, viaLine, ctaLine, "#PropTrading"];
    text = partsNoSummary.join("\n\n");
  }

  return text;
}

/**
 * Generate a tweet draft for the given rank-1 YouTube pick.
 */
export async function generateTweetDraft(pick: YouTubePickInput): Promise<TweetDraft> {
  const newsUrl = `${getNewsBaseUrl()}/news?${UTM_PARAMS}`;
  const hook = await generateHook(pick.title, pick.channelName, pick.aiSummary);
  const template: "A" | "B" = pick.twitterHandle ? "A" : "B";
  const creatorHandle = pick.twitterHandle ?? null;

  const tweetText = assembleTweet(
    hook,
    pick.aiSummary,
    pick.videoUrl,
    newsUrl,
    creatorHandle
  );

  // charCount uses Twitter's URL-shortening rules (each URL = 23 chars).
  // The raw string may be longer; that's fine — Twitter accepts it.
  function twitterCharCount(text: string): number {
    const urlMatches = text.match(/https?:\/\/\S+/g) ?? [];
    let len = text.length;
    for (const url of urlMatches) {
      len = len - url.length + TWITTER_URL_CHAR_COUNT;
    }
    return len;
  }

  const charCount = twitterCharCount(tweetText);

  return {
    tweetText,
    template,
    creatorHandle,
    videoTitle: pick.title,
    videoUrl: pick.videoUrl,
    newsUrl,
    charCount,
  };
}
